### ISSUE TITLE
Doesn't work with V6

### ISSUE THREAD

**Issue by unityweb** [sirportly/whmcs#1]
Hi, 

I already opened a ticket for this (a month ago) but it seems that you didn't upgrade your modules to be working with WHMCS v6. Can you please fix this as soon as possible ? We need to upgrade to V6 and this module is preventing us. Thanks !

**Comment by danquinney** [comment]
I'm just waiting on WHMCS to provide documentation for their support module framework, once I have this we'll be starting work on a version that is compatible with v6.

**Comment by unityweb** [comment]
Hi Dan, 
Still no update ? 

Thanks !

---

Cem KOKER
Account Manager / CTO

Unity Web Sàrl
rue du valais, 9

1202 Genève
Suisse

Tel : +41 22 732 72 70
Fax : +41 22 732 72 80

**Comment by danquinney** [comment]
I'm afraid not, once I have further information I'll update this issue.

**Comment by markbakeruk** [comment]
Hi Dan,

Have you made any progress with this at all?

I'm guessing it needs to make use of the Hooks functionality? http://docs.whmcs.com/Hooks 

Let me know what help / information you need from WHMCS and I'll be happy to assist.

**Comment by danquinney** [comment]
Hi Mark,

I've made great progress today so I hope to have the first alpha release out in the next day or two. I'll update this issue once the release is available.

Dan

**Comment by pixelpaulaus** [comment]
i also need this for v6 if possible?

**Comment by danquinney** [comment]
https://github.com/sirportly/whmcs/tree/master/v6
