### ISSUE TITLE
Data frame error after upgrade to WHMCS 7.2.2

### ISSUE THREAD

**Issue by markbakeruk** [sirportly/whmcs#11]
We're seeing an error in the data frame when a valid user is found since the upgrade of WHMCS to 7.2.2.

The error displayed in the browser is:

`Unable to connect to XXX WHMCS. Please check your settings or review the log files on your remote endpoint.`

and in the apache error logs:

`[16-Jun-2017 10:11:28 Europe/London] [WHMCS Application] ERROR: Error: Call to a member function getResponseFormat() on unknown in /clients/includes/api/getclientsdetails.php:0 Stack trace: #0 /clients/includes/functions.php(0): unknown() #1 /clients/modules/support/sirportly/frame.php(68): localAPI('getclientsdetai...', Array, 1) #2 {main} {"exception":"[object] (Error(code: 0): Call to a member function getResponseFormat() on unknown at /clients/includes/api/getclientsdetails.php:0)"} []​`

Has anyone else had this and found a fix?

**Comment by spheron1** [comment]
This is a known issue with WHMCS 7.2.2 and not something specific to the Sirportly support module. You need to install the CORE-11346 hotfix in order to resolve this - see https://forums.whmcs.com/showthread.php?129786-CORE-11346-Call-to-a-member-function-getResponseFormat()-on-null-Error

**Comment by markbakeruk** [comment]
Thanks Ed - didn't realise WHMCS only announced hot fixes via the forum - have now subscribed.

**Comment by spheron1** [comment]
At least they announce them now rather than just silently updating the download without bumping the version! ;)
