### ISSUE TITLE
Attachments not working

### ISSUE THREAD

**Issue by markbakeruk** [sirportly/whmcs#12]
A ticket raised, or a reply sent to a ticket via WHMC with an attachment sees the attachment disappear - it's simply not added to the ticket.

Is this a known bug, that someone else has perhaps fixed themselves? 

Appears to have been an issue since the first version of the code.

**Comment by spheron1** [comment]
We've had customers report this, although we haven't been able to reproduce it with our own (limited) testing.

**Comment by danquinney** [comment]
Does this happen consistently?

Could you turn on request and response logging for the API token and try to upload an attachment and let me know the responde details - feel free to drop them over in an email if you'd prefer. :)

**Comment by spheron1** [comment]
It seems to happen consistently for the customers who report it. I'll do some more testing to try and reproduce it.

**Comment by markbakeruk** [comment]
Sorry Dan, not getting e-mail alerts of replies here so missed this.

This happens constantly for us, and I've popped in a ticket which now also has the API logs on - I believe Adam has the ticket :-) 

Thanks

**Comment by spheron1** [comment]
It sounds like we may be having a slightly different problem, we're getting a "_The following errors occurred: The file you tried to upload is not allowed._" error message, which I have just been able to resolve by removing spaces from the "Allowed File Attachment Types" setting in Setup->General Settings->Support in WHMCS.

**Comment by markbakeruk** [comment]
Yup different issue, we get no error, just no attachment appears on the ticket.

Diagnostics are showing what I expect should be array of attachments is just empty, and the Sirportly team are looking at the issue, so hopefully we'll have a fix soon.

**Comment by markbakeruk** [comment]
This was resolved some time ago,
