### ISSUE TITLE
v6+ module: SIX skin hook seems to not fully work

### ISSUE THREAD

**Issue by dkoster** [sirportly/whmcs#3]
Dear Dan,

I've upgraded the sirportly module from v5+ to v6+ to match the WHMCS version running.
And at first glance it looks fine, but when logging in as a customer, it looks like the hook isn't working perfectly.

The " Recent Support Tickets " part and the "Ticket" block both report 0 tickets.
But clicking on the "Ticket" block, it returns 5 entries, 1 resolved, 4 new tickets.
How come?

Greetz,

Dennis

**Comment by danquinney** [comment]
This issue has now been resolved and the correct ticket counts are now returned.
