### ISSUE TITLE
v6+ module: Customer Data Source (api.php) / Customer Data Frame (frame.php) missing ?

### ISSUE THREAD

**Issue by dkoster** [sirportly/whmcs#4]
Dear Dan,

I'm looking for the new frame.php/api.php to link sirportly to whmcs.
Are they still in the process of development? When can we expect them ?

**Comment by danquinney** [comment]
We wanted to get the main module out as soon as we were able to as it had been delayed whilst waiting on information from WHMCS which meant we shipped without the frame or source files.

I do plan on adding these items however I'm not able to give a timeframe due to current commitments.

**Comment by danquinney** [comment]
Data frames have now been implemented in the new v6 module.

**Comment by simonhamp** [comment]
@danquinney are there any instructions anywhere on how to use DataFrames with WHMCS? (Sorry if it's really obvious, I haven't had time to hunt around very much)

**Comment by danquinney** [comment]
I've just written some documentation for setting up the data frames; https://github.com/sirportly/whmcs/blob/master/v6/readme.MD#customer-data-frame

**Comment by simonhamp** [comment]
👍 Thanks @danquinney. Legendary
