### ISSUE TITLE
frame.php

### ISSUE THREAD

**Issue by dkoster** [sirportly/whmcs#6]
Dear Dan,

Thanks for adding the frame.php, this works fine.
However it only works with main contacts and not with sub-accounts.

**Comment by danquinney** [comment]
That's correct Dennis however this is the same as the previous version of the frame, I'm happy to accept pull requests if you'd like to add this functionality.

**Comment by danquinney** [comment]
Thanks for that Dennis, I'm just merged this pull request for you.

Have a great weekend!
